name: Terraform Plan Workflow

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  detect-submodules:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - id: set-matrix
        run: |
          DIRS=$(find terraform/_modules -mindepth 1 -maxdepth 1 -type d)
          MATRIX_JSON="["
          for dir in $DIRS; do
            MATRIX_JSON+="{\"directoryPath\":\"$dir\"},"
          done
          MATRIX_JSON="${MATRIX_JSON%,}]"
          MATRIX_JSON+="]"
          echo "matrix=$MATRIX_JSON" >> $GITHUB_OUTPUT
          echo "Detected modules: $MATRIX_JSON"

  terraform-plan:
    needs: detect-submodules
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJson(needs.detect-submodules.outputs.matrix) }}

    defaults:
      run:
        working-directory: ${{ matrix.directoryPath }}

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - run: terraform init
      - run: terraform validate
      - run: terraform plan