name: Terraform Plan Workflow

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: set-matrix
        run: |
          CHANGED_DIRS=$(git diff HEAD^ HEAD --name-only -- '*.tf' | grep '^_modules/' || true)

          if [ -z "$CHANGED_DIRS" ]; then
            echo "No .tf changes found. Skipping matrix."
            echo "matrix=[]" >> $GITHUB_OUTPUT
          else
            DIR_LIST=$(echo "$CHANGED_DIRS" | xargs -n1 dirname | sort | uniq)
            MATRIX_JSON="["
            for dir in $DIR_LIST; do
              MATRIX_JSON+="{\"directoryPath\":\"$dir\"},"
            done
            MATRIX_JSON="${MATRIX_JSON%,}"  # remove trailing comma
            MATRIX_JSON+="]"
            echo "matrix=$MATRIX_JSON" >> $GITHUB_OUTPUT
            echo "Matrix: $MATRIX_JSON"
          fi

  terraform-plan:
    #if: needs.detect-changes.outputs.matrix != '[]'
    needs: detect-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJson(needs.detect-changes.outputs.matrix || '[{"directoryPath":"terraform/_modules/your_module"}]') }}

    defaults:
      run:
        working-directory: ${{ matrix.directoryPath }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - run: terraform init
      - run: terraform validate
      - run: terraform plan