name: Terraform Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual runs

permissions:
  id-token: write
  contents: read

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.detect_changes.outputs.matrix }}
      has_changes: ${{ steps.detect_changes.outputs.has_changes }}
      modules_changed: ${{ steps.detect_changes.outputs.modules_changed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history for git diff

      - name: Fetch origin/main
        run: git fetch origin main

      - name: Detect Terraform changes
        id: detect_changes
        run: |
          set -e
          # Check for prior runs (simplified: assume first run if no matrix output)
          PRIOR_RUNS=$(gh run list --workflow=terraform.yml --branch=main --limit=1 --json conclusion --jq '.[0].conclusion')
          echo "Prior runs conclusion: $PRIOR_RUNS"
          if [ -z "$PRIOR_RUNS" ]; then
            echo "First run detected, will plan all environments."
            ALL_DIRS=$(find . -maxdepth 1 -type d -not -path '.' -not -path './_modules' -not -path './_modules/*' | sort)
            VALID_DIRS=""
            for dir in $ALL_DIRS; do
              dir_path="${dir#./}"
              if ls "$dir"/*.tf >/dev/null 2>&1; then
                VALID_DIRS="$VALID_DIRS $dir_path"
              fi
            done
            if [ -z "$VALID_DIRS" ]; then
              echo "No Terraform environment directories found."
              echo "matrix=[]" >> $GITHUB_OUTPUT
              echo "has_changes=false" >> $GITHUB_OUTPUT
              echo "modules_changed=false" >> $GITHUB_OUTPUT
              exit 0
            fi
            JSON_MATRIX="["
            for dir in $VALID_DIRS; do
              sanitized_path=$(echo "$dir" | sed 's/"/\\"/g')
              JSON_MATRIX+="{\"directoryPath\":\"$sanitized_path\"},"
            done
            JSON_MATRIX=${JSON_MATRIX%,}
            JSON_MATRIX+="]"
            echo "Valid Terraform directories (first run): $VALID_DIRS"
            echo "matrix=$JSON_MATRIX" >> $GITHUB_OUTPUT
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "modules_changed=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          # Normal run: detect changes
          CHANGED_FILES=$(git diff origin/main HEAD --name-only -- '*.tf' || true)
          echo "Changed files: $CHANGED_FILES"
          # Check if _modules changed
          MODULES_CHANGED=$(echo "$CHANGED_FILES" | grep '^_modules/' || true)
          if [ -n "$MODULES_CHANGED" ]; then
            echo "_modules changed, planning all environments."
            ALL_DIRS=$(find . -maxdepth 1 -type d -not -path '.' -not -path './_modules' -not -path './_modules/*' | sort)
            VALID_DIRS=""
            for dir in $ALL_DIRS; do
              dir_path="${dir#./}"
              if ls "$dir"/*.tf >/dev/null 2>&1; then
                VALID_DIRS="$VALID_DIRS $dir_path"
              fi
            done
            if [ -z "$VALID_DIRS" ]; then
              echo "No Terraform environment directories found."
              echo "matrix=[]" >> $GITHUB_OUTPUT
              echo "has_changes=false" >> $GITHUB_OUTPUT
              echo "modules_changed=true" >> $GITHUB_OUTPUT
              exit 0
            fi
            JSON_MATRIX="["
            for dir in $VALID_DIRS; do
              sanitized_path=$(echo "$dir" | sed 's/"/\\"/g')
              JSON_MATRIX+="{\"directoryPath\":\"$sanitized_path\"},"
            done
            JSON_MATRIX=${JSON_MATRIX%,}
            JSON_MATRIX+="]"
            echo "Valid Terraform directories (_modules changed): $VALID_DIRS"
            echo "matrix=$JSON_MATRIX" >> $GITHUB_OUTPUT
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "modules_changed=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          # Check environment-specific changes
          CHANGED_DIRS=$(echo "$CHANGED_FILES" | awk -F'/' 'NF >= 1 {print $1}' | sort | uniq | grep -v '^_modules' || true)
          echo "Changed directories: $CHANGED_DIRS"
          if [ -z "$CHANGED_FILES" ] || [ -z "$CHANGED_DIRS" ]; then
            echo "No Terraform changes detected."
            echo "matrix=[]" >> $GITHUB_OUTPUT
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "modules_changed=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          VALID_DIRS=""
          for dir in $CHANGED_DIRS; do
            if [ -d "$dir" ] && ls "$dir"/*.tf >/dev/null 2>&1; then
              VALID_DIRS="$VALID_DIRS $dir"
            fi
          done
          if [ -z "$VALID_DIRS" ]; then
            echo "No valid Terraform environment directories changed."
            echo "matrix=[]" >> $GITHUB_OUTPUT
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "modules_changed=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          JSON_MATRIX="["
          for dir in $VALID_DIRS; do
            sanitized_path=$(echo "$dir" | sed 's/"/\\"/g')
            JSON_MATRIX+="{\"directoryPath\":\"$sanitized_path\"},"
          done
          JSON_MATRIX=${JSON_MATRIX%,}
          JSON_MATRIX+="]"
          echo "Valid Terraform directories (env changes): $VALID_DIRS"
          echo "matrix=$JSON_MATRIX" >> $GITHUB_OUTPUT
          echo "has_changes=true" >> $GITHUB_OUTPUT
          echo "modules_changed=false" >> $GITHUB_OUTPUT
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  tf_plan:
    runs-on: ubuntu-latest
    needs: check_changes
    if: ${{ needs.check_changes.outputs.has_changes == 'true' }}
    strategy:
      matrix:
        directoryPath: ${{ fromJson(needs.check_changes.outputs.matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug matrix input
        run: |
          echo "Matrix input: ${{ toJson(matrix) }}"
          echo "Current directoryPath: ${{ matrix.directoryPath }}"
        shell: bash

      - name: Debug directory contents
        run: |
          echo "Processing directory: ${{ matrix.directoryPath }}"
          if [ -d "${{ matrix.directoryPath }}" ]; then
            ls -la "${{ matrix.directoryPath }}"
          else
            echo "Directory ${{ matrix.directoryPath }} does not exist"
            exit 1
          fi
        shell: bash

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ matrix.directoryPath }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ matrix.directoryPath }}

      - name: Terraform Plan
        run: terraform plan
        working-directory: ${{ matrix.directoryPath }}