name: Plan-Apply Pipeline

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.detect_changes.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch origin/main
        run: git fetch origin main

      - name: Detect Terraform changes
        id: detect_changes
        run: |
          set -e
          CHANGED_FILES=$(git diff origin/main HEAD --name-only -- '*.tf' || true)
          echo "Changed files: $CHANGED_FILES"
          CHANGED_DIRS=$(echo "$CHANGED_FILES" | grep -v '^_modules' | awk -F'/' 'NF >= 1 {print $1}' | sort | uniq)
          echo "Changed directories (pre-filter): $CHANGED_DIRS"
          if [ -z "$CHANGED_DIRS" ]; then
            echo "No Terraform changes detected."
            echo "matrix={}" >> $GITHUB_OUTPUT
            exit 0
          fi
          JSON_MATRIX="{"
          for dir in $CHANGED_DIRS; do
            if [ -n "$dir" ]; then
              JSON_MATRIX+="\"$dir\":{\"directoryPath\":\"$dir\"},"
            fi
          done
          JSON_MATRIX=${JSON_MATRIX%,}
          JSON_MATRIX+="}"
          echo "Changed directories: $CHANGED_DIRS"
          echo "matrix=$JSON_MATRIX" >> $GITHUB_OUTPUT
        shell: bash

  tf_plan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directoryPath: ${{ fromJson(steps.find_dirs.outputs.matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find all Terraform directories
        id: find_dirs
        run: |
          set -e
          # Find directories containing .tf files, excluding _modules
          TF_DIRS=$(find . -type f -name '*.tf' -not -path '*/_modules/*' | sed 's|/[^/]*$||' | sort | uniq)
          if [ -z "$TF_DIRS" ]; then
            echo "No Terraform directories found."
            echo "matrix=[]" >> $GITHUB_OUTPUT
            exit 0
          fi
          # Validate each directory has a main.tf or similar
          VALID_DIRS=""
          JSON_MATRIX="["
          for dir in $TF_DIRS; do
            # Convert ./dir to dir, ./ to .
            if [ "$dir" = "." ]; then
              dir_path="."
            else
              dir_path="${dir#./}"
            fi
            # Check for at least one .tf file directly in the directory
            if ls "$dir"/*.tf >/dev/null 2>&1; then
              VALID_DIRS="$VALID_DIRS $dir_path"
              JSON_MATRIX+="{\"directoryPath\":\"$dir_path\"},"
            else
              echo "Skipping $dir_path: no .tf files directly in directory"
            fi
          done
          JSON_MATRIX=${JSON_MATRIX%,}
          JSON_MATRIX+="]"
          if [ -z "$VALID_DIRS" ]; then
            echo "No valid Terraform directories found."
            echo "matrix=[]" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "Valid Terraform directories: $VALID_DIRS"
          echo "matrix=$JSON_MATRIX" >> $GITHUB_OUTPUT
        shell: bash

      - name: Debug directory contents
        run: |
          echo "Processing directory: ${{ matrix.directoryPath }}"
          ls -la "${{ matrix.directoryPath }}"
        shell: bash

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ matrix.directoryPath }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ matrix.directoryPath }}

      - name: Terraform Plan
        run: terraform plan
        working-directory: ${{ matrix.directoryPath }}