name: plan-apply pipeline

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

stages:
- stage: tf_plan
  condition: ne(variables.isMain, 'True')
  jobs:
    - job: check_changes
      runs-on: ubuntu-latest
      steps:
        - checkout: self  # Changed to Azure DevOps syntax; use actions/checkout@v4 for GitHub Actions
        - script: |
            CHANGED_DIRS=$(git diff origin/main HEAD --name-only -- '*.tf' | grep -v '^_modules' | awk -F'/' 'NF > 1 {print $1}' | sort | uniq)
            JSON_MATRIX="{"
            for dir in $CHANGED_DIRS; do
              JSON_MATRIX+="\"$dir\":{\"directoryPath\":\"$dir\"},"
            done
            JSON_MATRIX=${JSON_MATRIX%,}
            JSON_MATRIX+="}"
            echo "Changed directories: $CHANGED_DIRS"
            echo "Matrix JSON: $JSON_MATRIX"
            echo "##vso[task.setvariable variable=matrix;isOutput=true]$JSON_MATRIX"
          displayName: 'Fetch latest Changes'
          name: detect_changes

    - job: tf_plan
      runs-on: ubuntu-latest
      dependsOn: check_changes
      condition: ne(dependencies.check_changes.outputs['detect_changes.matrix'], '')
      strategy:
        matrix: $[ dependencies.check_changes.outputs['detect_changes.matrix'] ]
      steps:
        - task: TerraformInstaller@1
          displayName: Install Terraform
          inputs:
            terraformVersion: 'latest'

        - task: AzureCLI@2
          name: tf_init_validate_plan
          displayName: Terraform init Validate & Plan
          inputs:
            azureSubscription: |
              client-id: ${{ secrets.AZURE_CLIENT_ID }}
              tenant-id: ${{ secrets.AZURE_TENANT_ID }}
              subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            script: |
              terraform init
              terraform validate
              terraform plan
            workingDirectory: '$(System.DefaultWorkingDirectory)/${{ matrix.directoryPath }}'
            visibleAzLogin: false