name: Terraform Plan

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Inspect repository contents
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing all files in workspace:"
          ls -la
          echo "Listing _modules/ recursively:"
          if [ -d "_modules/" ]; then
            ls -R _modules
          else
            echo "Directory _modules/ does not exist in the repository"
          fi
          echo "Listing tracked files in repository:"
          git ls-files _modules || echo "No files found under terraform/_modules in git"

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Loop through each module and plan
        run: |
          if [ ! -d "_modules" ]; then
            echo "Error: _modules directory not found in the repository"
            exit 1
          fi
          found_tf_files=false
          for dir in $(find _modules -type f -name "*.tf" -exec dirname {} \; | sort -u); do
            found_tf_files=true
            if [ -d "$dir" ]; then
              echo "Running Terraform in $dir"
              cd "$dir"
              terraform init
              terraform validate
              terraform plan
              cd - > /dev/null
            else
              echo "Directory $dir does not exist, skipping"
            fi
          done
          if [ "$found_tf_files" = false ]; then
            echo "No .tf files found in _modules/"
            exit 1
          fi